# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Model_pb2 as Model__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchInfo = channel.unary_stream(
                '/InfoService/FetchInfo',
                request_serializer=Model__pb2.Empty.SerializeToString,
                response_deserializer=Model__pb2.Info.FromString,
                _registered_method=True)
        self.UpdateInfo = channel.unary_unary(
                '/InfoService/UpdateInfo',
                request_serializer=Model__pb2.Info.SerializeToString,
                response_deserializer=Model__pb2.Empty.FromString,
                _registered_method=True)
        self.Offer = channel.unary_unary(
                '/InfoService/Offer',
                request_serializer=Model__pb2.MirrorInfo.SerializeToString,
                response_deserializer=Model__pb2.MirrorInfo.FromString,
                _registered_method=True)


class InfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Offer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchInfo,
                    request_deserializer=Model__pb2.Empty.FromString,
                    response_serializer=Model__pb2.Info.SerializeToString,
            ),
            'UpdateInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInfo,
                    request_deserializer=Model__pb2.Info.FromString,
                    response_serializer=Model__pb2.Empty.SerializeToString,
            ),
            'Offer': grpc.unary_unary_rpc_method_handler(
                    servicer.Offer,
                    request_deserializer=Model__pb2.MirrorInfo.FromString,
                    response_serializer=Model__pb2.MirrorInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('InfoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/InfoService/FetchInfo',
            Model__pb2.Empty.SerializeToString,
            Model__pb2.Info.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/InfoService/UpdateInfo',
            Model__pb2.Info.SerializeToString,
            Model__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Offer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/InfoService/Offer',
            Model__pb2.MirrorInfo.SerializeToString,
            Model__pb2.MirrorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
